### ISSUE TITLE
Issues Setting up Mattermost

### ISSUE THREAD

**Issue by anthonyrom** [tyler43636/docker-templates#1]
Hey, thanks for making this docker template. I'm using UnRaid, and installed the Mattermost docker template. When I click to the WebUI (or try to access 192.168.x.x:8065 where it should be), nothing loads. What additional configuration or setup is needed to get this working?

**Comment by anthonyrom** [comment]
This is what shows up in UnRaid's logs for Mattermost:

```
[info] Env var PUID defined as 99

[info] Env var PGID defined as 100

[info] Permissions already set for /mattermost

[info] Starting Supervisor...

2017-02-04 14:19:46,762 CRIT Supervisor running as root (no user in config file)

2017-02-04 14:19:46,762 WARN Included extra file "/etc/supervisor/conf.d/mattermost.conf" during 
parsing

2017-02-04 14:19:46,776 INFO RPC interface 'supervisor' initialized

2017-02-04 14:19:46,776 CRIT Server 'unix_http_server' running without any HTTP authentication 
checking

2017-02-04 14:19:46,776 INFO supervisord started with pid 17

2017-02-04 14:19:47,778 INFO spawned: 'mattermost' with pid 20

Need to set DB_HOST

2017-02-04 14:19:47,781 INFO exited: mattermost (exit status 1; not expected)

2017-02-04 14:19:48,784 INFO spawned: 'mattermost' with pid 21

Need to set DB_HOST

2017-02-04 14:19:48,794 INFO exited: mattermost (exit status 1; not expected)

2017-02-04 14:19:50,799 INFO spawned: 'mattermost' with pid 22

Need to set DB_HOST

2017-02-04 14:19:50,807 INFO exited: mattermost (exit status 1; not expected)

2017-02-04 14:19:53,813 INFO spawned: 'mattermost' with pid 23

Need to set DB_HOST

2017-02-04 14:19:53,822 INFO exited: mattermost (exit status 1; not expected)

2017-02-04 14:19:54,824 INFO gave up: mattermost entered FATAL state, too many start retries too 
quickly ```

**Comment by tyler43636** [comment]
Looks like the DB_HOST environment variable wasn't set. Try setting that and re-open if it doesn't work.

**Comment by anthonyrom** [comment]
I think I fixed that - I set a variable DB_HOST equal to the appdata directory I wanted. That error went away. 

Now I'm getting a new error (I will send the log after this) about DB_PORT. I have the port DB_PORT set to 8065 already (as it is by default), and I tried setting a variable DB_PORT to  8065. No luck. Nothing else is using that port as far as I know. What do I do?

**Comment by anthonyrom** [comment]
```
[info] Env var PUID defined as 99
[info] Env var PGID defined as 100
[info] Permissions already set for /mattermost
[info] Starting Supervisor...
2017-02-09 15:28:43,055 CRIT Supervisor running as root (no user in config file)
2017-02-09 15:28:43,055 WARN Included extra file "/etc/supervisor/conf.d/mattermost.conf" during parsing
2017-02-09 15:28:43,068 INFO RPC interface 'supervisor' initialized
2017-02-09 15:28:43,068 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-02-09 15:28:43,068 INFO supervisord started with pid 18
2017-02-09 15:28:44,070 INFO spawned: 'mattermost' with pid 21
Configure database and email settings
SKIP
Starting mattermost
[15:28:44 PST 2017/02/09] [INFO] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:56) Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
2017-02-09 15:28:45,111 INFO success: mattermost entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
panic: Failed to open sql connection dial tcp: unknown port tcp/DB_PORT


goroutine 1 [running]:
panic(0xb68f00, 0xc82050a0a0)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mattermost/platform/store.setupConnection(0xd8a010, 0x6, 0xc820264558, 0x5, 0xc820524510, 0x2c, 0xa, 0xa, 0xc820264f00, 0x2b833e5d3000)
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:218 +0x894
github.com/mattermost/platform/store.initConnection(0x41ba01)
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:63 +0x11b
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:85 +0x49
github.com/mattermost/platform/api.NewServer()
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/api/server.go:36 +0xe8
main.main()
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:97 +0x967
2017-02-09 15:28:45,164 INFO exited: mattermost (exit status 2; expected)
```

**Comment by anthonyrom** [comment]
the `panic: Failed to open sql connection dial tcp: unknown port tcp/DB_PORT` is the main error as far as I can tell

**Comment by tyler43636** [comment]
The DB_HOST variable is meant to be the ip or domain name of the MYSQL host. Checkout the readme on the Mattermost repo.

https://github.com/tyler43636/unraid-mattermost

**Comment by anthonyrom** [comment]
Oh I feel stupid, I didn't even know about that. Do you know if it is possible to host the MySQL on the same UnRaid machine? Thanks for helping me

**Comment by tyler43636** [comment]
Yes, you can. I use a compatible alternative called Maria DB. Do you have the community applications plugin installed? If so, just search mariadb. I use the one from Linuxserver.io.

Glad I can help. This stuff took me forever to figure out so glad to share.

**Comment by anthonyrom** [comment]
Installed MariaDB, installed mattermost using your readme as a guide. Do I have to set anything up in MariaDB? Getting the following now:

```

[info] Env var PUID defined as 99
[info] Env var PGID defined as 100
[info] Permissions already set for /mattermost
[info] Starting Supervisor...
2017-02-09 21:12:33,974 CRIT Supervisor running as root (no user in config file)
2017-02-09 21:12:33,974 WARN Included extra file "/etc/supervisor/conf.d/mattermost.conf" during parsing
2017-02-09 21:12:33,987 INFO RPC interface 'supervisor' initialized
2017-02-09 21:12:33,987 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-02-09 21:12:33,988 INFO supervisord started with pid 17
2017-02-09 21:12:34,991 INFO spawned: 'mattermost' with pid 20
Configure database and email settings
SKIP
Starting mattermost
[21:12:35 PST 2017/02/09] [INFO] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:56) Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
2017-02-09 21:12:36,060 INFO success: mattermost entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
panic: Failed to open sql connection Error 1045: Access denied for user 'mattermost'@'172.17.0.1' (using password: YES)


goroutine 1 [running]:
panic(0xb68f00, 0xc82046f1d0)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mattermost/platform/store.setupConnection(0xd8a010, 0x6, 0xc82046e348, 0x5, 0xc82025c800, 0x36, 0xa, 0xa, 0xc820354200, 0x2ab6c14394b0)
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:218 +0x894
github.com/mattermost/platform/store.initConnection(0x41ba01)
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:63 +0x11b
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:85 +0x49
github.com/mattermost/platform/api.NewServer()
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/api/server.go:36 +0xe8
main.main()
/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:97 +0x967
2017-02-09 21:12:36,115 INFO exited: mattermost (exit status 2; expected)
```

where the key bit seems to be `panic: Failed to open sql connection Error 1045: Access denied for user 'mattermost'@'172.17.0.1' (using password: YES)`

172.17.0.1  is not the IP of my server by the way, i assume this needs to be changed but I'm not sure where or how to do it.

**Comment by tyler43636** [comment]
The IP of the database server is set at first run from the DB_HOST variable. There are two ways to change it.

1) Delete the config.json file and reload the container. The file will be regenerated from the environment variables. 

2) Just edit the config.json file directly. You can set the database server IP there.

**Comment by anthonyrom** [comment]
Deleted everything and reinstalled - still getting same error. The config file [clearly shows the right IP address](https://gyazo.com/3909443d4ee23f466fc0ba4e04f06b54.png), however the logs still say the same thing about not being able to access 172.17.0.1.

Like I said, I have set up literally nothing in MariaDB (and don't know how) so I assume that is the issue? What do I need to do/create in terms of SQL/databases to get this up and running?

**Comment by tyler43636** [comment]
First, get to a bash shell inside the container.
```docker exec -it {container-name} /bin/bash```
Next, connect to the database.
```mysql -u root -p```
Then, create a new database.
```CREATE DATABASE database-name;```

DigitalOcean has a really tutorial on MYSQL.
https://www.digitalocean.com/community/tutorials/a-basic-mysql-tutorial

**Comment by anthonyrom** [comment]
How do I figure out the root password which is asked for by `mysql -u root -p`? I can't get past that, which seems to be my error (since the previous logs also had trouble logging into the sql thing)

**Comment by tyler43636** [comment]
You would have set it up when you created the MariaDB container. Check out the documentation on the linuxserver.io's MariaDB page.

https://hub.docker.com/r/linuxserver/mariadb/

**Comment by anthonyrom** [comment]
Cool, thank you. Turns out my problem was that I didn't change the sql username from mattermost to the correct one.

Now the logs show no errors, but when I go to webui for mattermost (ip_address:8065), it says page unavailable. Is there something else I need to do to get it working?

Included logs:
```
[info] Env var PUID defined as 1000
[info] Env var PGID defined as 100
[info] Setting permissions recursively on /config...
[info] Starting Supervisor...
2017-02-13 20:00:09,933 CRIT Supervisor running as root (no user in config file)
2017-02-13 20:00:09,933 WARN Included extra file "/etc/supervisor/conf.d/mattermost.conf" during parsing
2017-02-13 20:00:09,946 INFO RPC interface 'supervisor' initialized
2017-02-13 20:00:09,946 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-02-13 20:00:09,946 INFO supervisord started with pid 19
2017-02-13 20:00:10,949 INFO spawned: 'mattermost' with pid 22
Configure database and email settings
OK
Starting mattermost
[20:00:11 PST 2017/02/13] [INFO] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:56) Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
2017-02-13 20:00:12,035 INFO success: mattermost entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by tyler43636** [comment]
Sounds like the port may have not been exposed from docker. Are you using unraid?

**Comment by anthonyrom** [comment]
Yes I am

**Comment by tyler43636** [comment]
Send me a screenshot of the config page in unraid.

**Comment by anthonyrom** [comment]
I'm not sure what the issue was - I reinstalled from the beginning and everything worked. Thank you so much for all your help!
